### PR TITLE
new face detector using OpenCV combined with FaceMesh

### PR DESCRIPTION
**Pull request by nothings**
The goal is to make a face detector that detects smaller faces without having to specify subdivision into multiple subimages, so it can just work automatically when processing batches.

To do this, I use OpenCV2's face detector to find rectangles that might be faces, then use the existing FaceMesh code to confirm that the face is real and to get the landmarks to be able to get a mask from it.

Here are the results I get in this version (test X is 32 images, test Y is 176 images, time is number of seconds to detect the faces using Mask Only mode):

|method|faces X|time X|faces Y|time Y|
|--|--|--|--|--|
|original (FaceMesh), 1x1 subimages |30|1.0|136|6.3|
|original (FaceMesh), 3x3 subimages |166|3.5|1063|15.8|
|original (FaceMesh), 5x5 subimages |262|6.2|1849|36.3|
|new (OpenCV) Normal, 30pix minimum |282|4.8|2273|34.0|
|new (OpenCV) Slow, 30pix minimum   |333|23.4|2624|171.6|
|new (OpenCV) Extremely Slow, 30pix minimum|370|130.8|2802|1080.5|

I made a web page showing the masks generated for the 32 images, [it's here](http://nothings.org/ai/face-detect). None of these images were chosen specifically to break the old detector, but I didn't test anything with fewer than 3 faces so obviously that affects the results; the numbers don't reflect the easy cases where both will do equally well.

Some specific cases to notice:
- OpenCV always gets cases like 01-04.
- Both face detectors recognize faces of people wearing masks in 08 and 14! I wasn't expecting this, but figured I'd test it.
- 11 shows how it can be hard to find a setting with the old detector that finds all the faces.
- 12 is an example where the 5th face (further back) is only found by Extremely Slow.
- 15, 16, 23, and 26 are ones where the old detector finds more faces than the new one, but only if you find the right subdivision. I think OpenCV can find it with an even slower mode, which maybe is possible if I optimize (see below).
- For 24, OpenCV never finds the faces at all even though FaceMesh can find them. There's a separate "face in profile" detector that might address this, I'll play with that after this PR goes through.
- 25 is a weird tie with Extremely Slow (both approaches find 5 faces, but not the same ones).

You can see sometimes with 3x3 and 5x5 the face is detected, but it was cropped so the mask has a straight line across it. It might still be okay, I didn't actually test face-swapping those specifically.

More details about how the new detector works:
- First it runs the old detector. OpenCV sometimes misses large faces unless you set it to run even slower than Extremely Slow.
- Next it runs the OpenCV face detector to collect rectangles that might be faces.
- Then it crops the image around each face. FaceMesh only likes faces that are a certain size. Some thorough testing gave me the best results by using a crop that was 4x the face rectangle width, and 2.5x the face rectangle height.
- It gives the cropped image to FaceMesh, which returns (potentially) multiple faces.
- It takes the face landmarks from FaceMesh, finds their convex hulls, computes the bounding boxes, and then looks for a bounding box that overlaps significantly with the OpenCV face rectangle that corresponds to this specific crop.
- If it doesn't find a match with FaceMesh, it adds one to a `rejected` counter which we print if in development mode (see below)

Some things to know / issues to consider:
- There's a new dropdown to select which mode to use. It defaults to the old mode. I'd prefer it to default to the fastest new mode, which I think is a good compromise, but that's up to you. Change `DEFAULT` in face_detect.py.
- I moved all the face detection logic into face_detect.py since there's a lot of code.
- All the subdivision code is still there and still working. If you think the new thing is good enough you might want to get rid of all that code and simplify the UI, but maybe it's better to keep it for people who like the old way. Up to you!
- There's an accompanying slider to set the minimum face size, because this is a parameter for OpenCV's face detector, and it seemed useful to let people say they don't want faces "in the background" detected.
- There's a debug UI controlled by the setting of `FaceDetectDevelopment` in face_detect.py
- I pass a new variable 'facecfg' all around lots of functions. It's primarily used to pass the debug UI settings. I'm not sure if the normal convention is to just put stuff on `p` if you need some kind of context like this, but it also needs to work if called from UpdateVisualizer so it's kind of messy.
- I had a bunch of messy trailing whitespaces in my new code so I used search-and-replace to clean that all up, but it also cleaned it up from your code, which makes the diff a bit messier, sorry.
- I hacked in a `faceDebug` function to save those masked images found on the web page (you have to turn on FaceDetectDevelopment to use it). It uses a hacky image save routine called "debugsave".  I didn't know the best way to specify an output directory for that, so if you want to change it to something saner (I use an environment variable) that's fine.
- None of this is tuned as well as I'd like. I got distracted by trying to optimize instead.
- There's a bunch of optimizations I tried but they're all disabled (at the end of face_detect.py). Some should be viable to make Extremely Slow faster, but I didn't fully understand the results I was getting, so I need more time to figure out what's really going on.
- Some stuff is heavily commented, some stuff isn't.
- This is my first time programming Python. I did a lot of googling to try to find the most Pythonic ways to do things, but there be some dumb stuff still.

I'm happy to make any changes you ask for!

### CODE REVIEW

**Comment by nothings** [comment]
Also, in my testing, sometimes FaceMesh alone could find 5 images, so I bumped the setting in the FaceMesh call up to 5 even in the old detector path. Could maybe make it 6 just in case.

**Comment by kex0** [comment]
This is beyond amazing. You've put some serious work into this and I really appreciate it.

I didn't read through the code yet but from my very limited testing, it works very good. I'll do some more extensive testing tomorrow, I have to get some sleep.

Nonetheless, I added you as a contributor to this repository, so feel free to merge this and add any changes you want.

I'm astonished from the amount and the quality of the work you put into this.

P.S. the "haarcascade_frontalface_default.xml" has to be included in the repository.

**Comment by nothings** [comment]
Added missing file.

**Comment by nothings** [comment]
I'll let you test it first, it's definitely possible I broke something since I didn't test all possible paths (I'm not sure I even know what they are). Once you've tested, you can push it or I can push it, either one is fine. Do read over the list at the end at the end of the submission there are things you'd like changed.

For future changes, I'll probably make a "dev" branch and push stuff that I work on to that and ask if you have any opinions on it, then we can push it to main afterwards.

**Comment by nothings** [comment]
It looks like the OpenCV detector is CPU not GPU, and it uses multiple CPUs. My machine has 16 cores, so results may be a lot slower on machines with fewer. Might be worth testing if you have a very different setup. (Most important thing to compare is 5x5 old detector vs. Normal new detector.)

But then again, maybe FaceMesh is the same, so it works out, I don't know.

**Comment by kex0** [comment]
> * I'd prefer it to default to the fastest new mode, which I think is a good compromise,

I agree.

> * All the subdivision code is still there and still working. If you think the new thing is good enough you might want to get rid of all that code and simplify the UI, but maybe it's better to keep it for people who like the old way. Up to you!

Do I understand it correctly that it first runs mediapipe, then OpenCV, crops the image and runs mediapipe on the cropped image? If so then all the subdivision code is pretty much useless considering that the new fastest way is much more reliable and  slightly faster than 5x5 subdivision.

It needlessly adds complexity for users so I think it can be completely removed.

> * This is my first time programming Python. I did a lot of googling to try to find the most Pythonic ways to do things, but there be some dumb stuff still.

I'm impressed that you managed to make some sense of my complete mess of a code. I'm sure you can tell I'm a beginner myself.

> I'll let you test it first, it's definitely possible I broke something since I didn't test all possible paths (I'm not sure I even know what they are). Once you've tested, you can push it or I can push it, either one is fine. Do read over the list at the end at the end of the submission there are things you'd like changed.

I tested everything I could think of and the new detection seems to work very well. I made some tiny UI changes but that's it. (not sure how to commit to this pull request, I'll try)

> For future changes, I'll probably make a "dev" branch and push stuff that I work on to that and ask if you have any opinions on it, then we can push it to main afterwards.

Good idea.

> It looks like the OpenCV detector is CPU not GPU, and it takes advantage of multiple CPUs. My machine has 16 cores, so results may be a lot slower on machines with fewer. Might be worth testing if you have a very different setup. (Most important thing to compare is 5x5 old detector vs. Normal new detector.)
> 
> But then again, maybe FaceMesh is the same, so it works out, I don't know.

Yeah, FaceMesh also uses CPU. My CPU is also quite beefy and I don't have access to anything much slower so I can't test it.

**Comment by nothings** [comment]
Woohoo!

**Comment by nothings** [comment]
> > * All the subdivision code is still there and still working. If you think the new thing is good enough you might want to get rid of all that code and simplify the UI, but maybe it's better to keep it for people who like the old way. Up to you!
> 
> Do I understand it correctly that it first runs mediapipe, then OpenCV, crops the image and runs mediapipe on the cropped image? If so then all the subdivision code is pretty much useless considering that the new fastest way is much more reliable and slightly faster than 5x5 subdivision.

That understanding is correct; the new detector still runs FaceMesh once for every potential face, just with a custom crop instead of an arbitrary subimage, so it's meant to replace the subdivision approach.

The only thing is that it's not 100% more reliable, as there are a few cases I listed where OpenCV didn't find a face that subdivided FaceMesh did. The new one always finds more faces overall in a large batch, but if you're working on a single image you could tweak the subdivision and sometimes, rarely, get more faces.

Personally I'm fine with getting rid of the subdivision complexity and losing some faces (and gaining more in return), and maybe over time I can address this and improve the results from the OpenCV detector with optimizations and tuning so it also finds those missing faces.

**Comment by kex0** [comment]
If we were to keep the subdivision code, maybe we could add [THIS](http://nothings.org/ai/face-detect/) to the README or to one of the tips in the webUI itself so users can more easily understand what's happening and how different detectors can affect the speed and the amount of detections.

**Comment by nothings** [comment]
Yeah, regardless we should definitely update the wiki, I don't think we need that full demo, but I'll definitely writeup some explanation of what's going on. I'm gonna let you decide whether to keep the subdivision code or not, but either way I'll write something up this weekend (if it's ok to wait that long).

**Comment by kex0** [comment]
> Yeah, regardless we should definitely update the wiki, I don't think we need that full demo,

Agreed. 

> I'm gonna let you decide whether to keep the subdivision code or not,

I think I will keep the subdivision code and just hide it in the UI if the old detection method isn't selected.

> either way I'll write something up this weekend (if it's ok to wait that long).

Sounds great. Of course it's ok.

**Comment by nothings** [comment]
I just pushed a chance so the UI defaults to using the fastest OpenCV mode.

**Comment by nothings** [comment]
Can I get an email address for you? There's something I want to discuss off of github. You can find my email address on my github profile page.

**Comment by kex0** [comment]
I sent you an email.

**Pull request merged**
